//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoQuangMinh_2210900042_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_GIAM_GIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_GIAM_GIA()
        {
            this.DON_HANG = new HashSet<DON_HANG>();
        }
    
        public int Ma_PGG { get; set; }
        public string Ma_GG { get; set; }
        public Nullable<decimal> So_tien_giam { get; set; }
        public Nullable<System.DateTime> Ngay_het_han { get; set; }
        public Nullable<bool> Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_HANG> DON_HANG { get; set; }
    }
}
