//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoQuangMinh_2210900042_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI
    {
        public int ID { get; set; }
        public string Tai_khoan { get; set; }
        public string Mat_lhau { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    }
}
